language: c

matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc
    addons:
      apt:
        packages:
        - libgc-dev
  #powerjobs
  - os: linux
    arch: ppc64le
    compiler: gcc
    addons:
      apt:
        packages:
        - libgc-dev
  
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bdw-gc  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgc-dev ; fi

script: autoreconf --install && automake --add-missing --copy && ./configure && make check
